[phases.setup.env]
JAVA_VERSION = "17"

[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.build]
cmds = ["mvn -B -DskipTests clean install"]

[start]
cmd = "java -jar target/theGuardiansEye-0.0.1-SNAPSHOT.jar"
